"""initial schema

Revision ID: 3581bee771c9
Revises:
Create Date: 2026-10-09 06:30:29.069938

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3581bee771c9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("action_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("rules_applied_json", sa.Text(), nullable=False),
        sa.Column("applied_at", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.Column("reverted_at", sa.Float(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("overridden_by", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("action_id"),
    )
    op.create_index(op.f("ix_actions_device_id"), "actions", ["device_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("opened_at", sa.Float(), nullable=False),
        sa.Column("closed_at", sa.Float(), nullable=True),
        sa.Column("peak_score", sa.Float(), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=False),
        sa.Column("explanation_json", sa.Text(), nullable=False),
        sa.Column("explanation_text", sa.Text(), nullable=False),
        sa.Column("likely_attack_json", sa.Text(), nullable=False),
        sa.Column("recommended_actions_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    op.create_index(op.f("ix_alerts_device_id"), "alerts", ["device_id"], unique=False)
    op.create_index(op.f("ix_alerts_opened_at"), "alerts", ["opened_at"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_table(
        "destinations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("dst_ip", sa.String(length=45), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.Float(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_destinations_device_id"), "destinations", ["device_id"], unique=False)
    op.create_index(
        "ix_destinations_device_ip_port",
        "destinations",
        ["device_id", "dst_ip", "port"],
        unique=True,
    )
    op.create_index(op.f("ix_destinations_dst_ip"), "destinations", ["dst_ip"], unique=False)
    op.create_table(
        "detections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("window_end", sa.Float(), nullable=False),
        sa.Column("ml_score", sa.Float(), nullable=False),
        sa.Column("stat_score", sa.Float(), nullable=False),
        sa.Column("net_score", sa.Float(), nullable=False),
        sa.Column("threat_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("level", sa.String(length=32), nullable=False),
        sa.Column("top_features_json", sa.Text(), nullable=False),
        sa.Column("triggers_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_detections_device_id"), "detections", ["device_id"], unique=False)
    op.create_index(
        "ix_detections_device_window", "detections", ["device_id", "window_end"], unique=False
    )
    op.create_index(op.f("ix_detections_window_end"), "detections", ["window_end"], unique=False)
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("mac", sa.String(length=17), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("first_seen", sa.Float(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_index(op.f("ix_devices_ip"), "devices", ["ip"], unique=False)
    op.create_table(
        "drift_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("detected_at", sa.Float(), nullable=False),
        sa.Column("drift_score", sa.Float(), nullable=False),
        sa.Column("p_value", sa.Float(), nullable=False),
        sa.Column("top_drifting_features_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drift_events_device_id"), "drift_events", ["device_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column("feedback_id", sa.String(length=64), nullable=False),
        sa.Column("alert_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("feedback_id"),
    )
    op.create_index(op.f("ix_feedback_alert_id"), "feedback", ["alert_id"], unique=False)
    op.create_index(op.f("ix_feedback_device_id"), "feedback", ["device_id"], unique=False)
    op.create_table(
        "models",
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("trained_at", sa.Float(), nullable=False),
        sa.Column("train_start_ts", sa.Float(), nullable=False),
        sa.Column("train_end_ts", sa.Float(), nullable=False),
        sa.Column("metrics_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_index(op.f("ix_models_device_id"), "models", ["device_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "windows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("window_start", sa.Float(), nullable=False),
        sa.Column("window_end", sa.Float(), nullable=False),
        sa.Column("vector_json", sa.Text(), nullable=False),
        sa.Column("n_packets", sa.Integer(), nullable=False),
        sa.Column("quality_flags_json", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_windows_device_id"), "windows", ["device_id"], unique=False)
    op.create_index(
        "ix_windows_device_time",
        "windows",
        ["device_id", "window_start", "window_end"],
        unique=False,
    )
    op.create_index(op.f("ix_windows_window_end"), "windows", ["window_end"], unique=False)
    op.create_index(op.f("ix_windows_window_start"), "windows", ["window_start"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_windows_window_start"), table_name="windows")
    op.drop_index(op.f("ix_windows_window_end"), table_name="windows")
    op.drop_index("ix_windows_device_time", table_name="windows")
    op.drop_index(op.f("ix_windows_device_id"), table_name="windows")
    op.drop_table("windows")
    op.drop_table("settings")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_models_device_id"), table_name="models")
    op.drop_table("models")
    op.drop_index(op.f("ix_feedback_device_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_alert_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_drift_events_device_id"), table_name="drift_events")
    op.drop_table("drift_events")
    op.drop_index(op.f("ix_devices_ip"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_detections_window_end"), table_name="detections")
    op.drop_index("ix_detections_device_window", table_name="detections")
    op.drop_index(op.f("ix_detections_device_id"), table_name="detections")
    op.drop_table("detections")
    op.drop_index(op.f("ix_destinations_dst_ip"), table_name="destinations")
    op.drop_index("ix_destinations_device_ip_port", table_name="destinations")
    op.drop_index(op.f("ix_destinations_device_id"), table_name="destinations")
    op.drop_table("destinations")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_opened_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_device_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_actions_device_id"), table_name="actions")
    op.drop_table("actions")
    # ### end Alembic commands ###
