"""
Unit tests for Milestone P3-1: Random Sub-Window Episode Start Offsets.
Verifies that episode start times do not align with window stride boundaries,
guaranteeing that Time-to-Detect (TTD) is strictly non-zero by physical design.
"""

import numpy as np

from guardian.eval.benchmarks import generate_scaled_fleet
from guardian.eval.runner import EvaluationRunner, OperatingPoint
from guardian.eval.scenario import (
    AttackIntensity,
    DifficultyTier,
    EvasionMode,
    ScenarioBuilder,
    calculate_sub_window_offset,
)
from simulation.attack_suite import AttackType


def test_calculate_sub_window_offset_bounds() -> None:
    """Verifies that calculate_sub_window_offset produces values strictly in (0, stride_s)."""
    rng = np.random.default_rng(42)
    stride_s = 2.0
    for _ in range(100):
        offset = calculate_sub_window_offset(stride_s=stride_s, rng=rng)
        assert 0.1 <= offset <= stride_s - 0.1, f"Offset {offset} outside expected bounds"


def test_scenario_builder_episodes_have_sub_window_offsets() -> None:
    """Verifies that episodes generated by ScenarioBuilder have non-integer stride offsets."""
    sb = ScenarioBuilder(seed=42, total_days=14, stride_s=2.0)
    episodes = sb.generate_ground_truth_schedule(episodes_per_attack=2)
    assert len(episodes) > 0

    for ep in episodes:
        # start_time modulo stride_s must not be 0.0 (not aligned with stride boundary)
        rem = ep.start_time % sb.stride_s
        assert rem > 0.05 and rem < (sb.stride_s - 0.05), (
            f"Episode {ep.episode_id} start_time={ep.start_time} coincides with stride boundary!"
        )


def test_sub_window_offset_guarantees_non_zero_ttd() -> None:
    """
    Verifies that running EvaluationRunner on episodes with sub-window offsets
    guarantees that time-to-detect (TTD) is strictly non-zero by design.
    """
    fleet = generate_scaled_fleet(1)
    dev = fleet[0]
    sb = ScenarioBuilder(seed=42, total_days=1, stride_s=2.0)
    runner = EvaluationRunner(
        seed=42,
        total_days=1,
        devices=fleet,
        operating_point=OperatingPoint(alert_threshold=40.0, frozen=True),
    )

    # Create episode with random sub-window start offset
    ep = sb.create_offset_episode(
        episode_id="ep_offset_ttd_test",
        device_id=dev.id,
        attack_type=AttackType.CNC_BEACONING,
        base_start_time=10.0,
        duration_seconds=20.0,
        intensity=AttackIntensity.MEDIUM,
        evasion_mode=EvasionMode.NONE,
        tier=DifficultyTier.MEDIUM,
    )

    res = runner.evaluate_device_slice(
        device_id=dev.id,
        start_time=0.0,
        end_time=40.0,
        episodes=[ep],
    )

    # TTD must be strictly greater than 0 by physical construction
    assert res.mean_time_to_detect_s > 0.0, (
        f"Expected non-zero TTD, got {res.mean_time_to_detect_s:.4f}s"
    )
    # The start time must not align with an integer stride
    assert ep.start_time % 2.0 != 0.0
