"""
Unit tests for Milestone P3-1: Real Evaluation Harness Broken Detectors Audit.
Proves empirically that Phase 2 metrics (F1 0.7907, 0.7000, and 0.5143) were exact artifacts
of an always-alerting classifier on the evaluation slice geometries.
"""

import numpy as np

from guardian.eval.benchmarks import generate_scaled_fleet
from guardian.eval.metrics import compute_binary_metrics
from guardian.eval.runner import EvaluationRunner, OperatingPoint
from guardian.eval.scenario import AttackIntensity, EvasionMode, GroundTruthEpisode
from simulation.attack_suite import AttackType


def test_always_alert_reproduces_phase2_fixed_f1_scores() -> None:
    """
    Empirically verifies that feeding an always-alert prediction into the real
    scenario stream window generator reproduces the Phase 2 F1 values:
    - 0.7907 on the Phase 2 detection slice geometry (P=17, N=9)
    - 0.7000 on the Phase 2 adversarial slice geometry (P=14, N=12)
    - 0.5143 on the Phase 2 delayed-start slice geometry (P=9, N=17)
    """
    fleet = generate_scaled_fleet(1)
    dev = fleet[0]
    runner = EvaluationRunner(
        seed=42,
        total_days=1,
        devices=fleet,
        operating_point=OperatingPoint(alert_threshold=40.0, frozen=True),
    )

    # 1. Phase 2 Detection slice: 60s slice with episode from 10.0 to 36.0 (P=17, N=9)
    ep_det = GroundTruthEpisode(
        episode_id="ep_audit_det",
        device_id=dev.id,
        attack_type=AttackType.CNC_BEACONING,
        start_time=10.0,
        end_time=36.0,
        duration_seconds=26.0,
        intensity=AttackIntensity.HIGH,
        evasion_mode=EvasionMode.NONE,
    )
    windows_det = runner.scenario_builder.generate_device_stream_windows(
        device_id=dev.id, start_time=0.0, end_time=60.0, episodes=[ep_det]
    )
    y_true_det = [1 if w.has_attack else 0 for w in windows_det]
    assert sum(y_true_det) == 17
    assert len(y_true_det) - sum(y_true_det) == 9

    always_pred_det = [1] * len(y_true_det)
    m_det = compute_binary_metrics(y_true_det, always_pred_det)
    assert round(m_det.f1, 4) == 0.7907, f"Expected 0.7907, got {m_det.f1:.4f}"

    # 2. Phase 2 Adversarial slice: 60s slice with episode from 10.0 to 30.0 (P=14, N=12)
    ep_adv = GroundTruthEpisode(
        episode_id="ep_audit_adv",
        device_id=dev.id,
        attack_type=AttackType.CNC_BEACONING,
        start_time=10.0,
        end_time=30.0,
        duration_seconds=20.0,
        intensity=AttackIntensity.MEDIUM,
        evasion_mode=EvasionMode.NONE,
    )
    windows_adv = runner.scenario_builder.generate_device_stream_windows(
        device_id=dev.id, start_time=0.0, end_time=60.0, episodes=[ep_adv]
    )
    y_true_adv = [1 if w.has_attack else 0 for w in windows_adv]
    assert sum(y_true_adv) == 14
    assert len(y_true_adv) - sum(y_true_adv) == 12

    always_pred_adv = [1] * len(y_true_adv)
    m_adv = compute_binary_metrics(y_true_adv, always_pred_adv)
    assert round(m_adv.f1, 4) == 0.7000, f"Expected 0.7000, got {m_adv.f1:.4f}"

    # 3. Phase 2 Delayed-Start slice: 60s slice with dormant period (P=9, N=17)
    ep_delay = GroundTruthEpisode(
        episode_id="ep_audit_delay",
        device_id=dev.id,
        attack_type=AttackType.CNC_BEACONING,
        start_time=10.0,
        end_time=30.0,
        duration_seconds=20.0,
        intensity=AttackIntensity.MEDIUM,
        evasion_mode=EvasionMode.DELAYED_START,
    )
    windows_delay = runner.scenario_builder.generate_device_stream_windows(
        device_id=dev.id, start_time=0.0, end_time=60.0, episodes=[ep_delay]
    )
    y_true_delay = [1 if w.has_attack else 0 for w in windows_delay]
    assert sum(y_true_delay) == 9
    assert len(y_true_delay) - sum(y_true_delay) == 17

    always_pred_delay = [1] * len(y_true_delay)
    m_delay = compute_binary_metrics(y_true_delay, always_pred_delay)
    assert round(m_delay.f1, 4) == 0.5143, f"Expected 0.5143, got {m_delay.f1:.4f}"


def test_never_alert_and_shuffled_labels_on_real_harness() -> None:
    """
    Verifies that never-alert and shuffled-label controls function accurately
    when evaluated on real stream windows generated by ScenarioBuilder.
    """
    fleet = generate_scaled_fleet(1)
    dev = fleet[0]
    runner = EvaluationRunner(
        seed=42,
        total_days=1,
        devices=fleet,
        operating_point=OperatingPoint(alert_threshold=40.0, frozen=True),
    )
    ep = GroundTruthEpisode(
        episode_id="ep_controls_harness",
        device_id=dev.id,
        attack_type=AttackType.CNC_BEACONING,
        start_time=10.0,
        end_time=30.0,
        duration_seconds=20.0,
        intensity=AttackIntensity.MEDIUM,
        evasion_mode=EvasionMode.NONE,
    )
    windows = runner.scenario_builder.generate_device_stream_windows(
        device_id=dev.id, start_time=0.0, end_time=60.0, episodes=[ep]
    )
    y_true = [1 if w.has_attack else 0 for w in windows]

    # Never alert
    never_pred = [0] * len(y_true)
    m_never = compute_binary_metrics(y_true, never_pred)
    assert m_never.tpr == 0.0
    assert m_never.fpr == 0.0
    assert m_never.f1 == 0.0

    # Shuffled labels control
    rng = np.random.default_rng(1234)
    y_shuffled = rng.permutation(y_true).tolist()
    m_shuffled = compute_binary_metrics(y_shuffled, [1] * len(y_true))
    # Always-alert on shuffled ground truth still gives TPR=1.0 and FPR=1.0
    assert m_shuffled.tpr == 1.0
    assert m_shuffled.fpr == 1.0
